### ISSUE TITLE
Projeto CRm

### ISSUE THREAD

**Issue by williamr8915** [vitchili/crm_acionamento#1]
Olá, vi que tem um projeto em andamento, talves até concluso de crm de cobrança. gostaria de falar contigo sobre um projeto similar para nossa empresa e ver se tem interesse em executa-lo. obrigado por hora.

**Comment by vieira-tecnol** [comment]
Boa tarde, William! Vamos conversar por whatsapp? Me chame quando puder ;)

+5531972248740

Valeu!
